### PR TITLE
Advanced Search & Dark Mode

### PR DESCRIPTION
**Pull request by 07Kaustubh**
Added advanced search features like author, date, rating, genre.
Imolemented dark mode switch in navbar by using state in app.js and changes in index.css

### CODE REVIEW

**Comment by ishitaraina1807** [comment]
Thanks for a good contribution!

**Comment by ishitaraina1807** [comment]
image
image

Text is not visible in the dark mode. Can you please fix it? 
And please give some padding or margin to these. 
Thank you.

**Comment by 07Kaustubh** [comment]
Working on it.

Also please add me to the team in caffeine and code.
Or

Share the team code asap

**Comment by ishitaraina1807** [comment]
Sorry what team?

**Pull request merged**
